# Generated by Django 5.1.3 on 2024-11-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_address_donor_phone_alter_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount_donated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
