# Generated by Django 5.1.3 on 2024-11-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_donor_amount_donated'),
        ('event', '0002_event_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='created_at',
        ),
        migrations.AddField(
            model_name='donor',
            name='country',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
