# Generated by Django 5.1.3 on 2024-11-26 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_remove_donor_created_at_donor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
