# Generated by Django 5.1.3 on 2024-11-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunteer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='gisele@rca.ac.rw', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default='0788748410', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
